import { defineAgent } from "./helpers";

export const customerServiceAgents = [
  defineAgent({
    slug: "customer-inquiry",
    personaName: "Mia",
    roleTitle: "Customer Inquiry Agent",
    department: "customer-service",
    tagline: "Standardfragen beantwortet — mit Quellen",
    description:
      "Beantwortet freigegebene Standardfragen aus der Wissensbasis, nennt nur belegte Informationen und eskaliert bei Unsicherheit an Menschen.",
    responsibilities: [
      "Freigegebene Standardfragen beantworten",
      "Die Wissensbasis mit Quellenangaben nutzen",
      "Nur belegte Informationen nennen",
      "Bei Unsicherheit an Menschen eskalieren",
    ],
    boundaries: [
      "Beantwortet nur Fragen, die durch die Wissensbasis gedeckt sind",
      "Eskaliert bei Unsicherheit, Beschwerden oder rechtlichen Themen",
      "Macht keine Zusagen außerhalb hinterlegter Regeln",
    ],
    kpis: [
      { key: "inquiries_answered", label: "Beantwortete Anfragen", unit: "Anzahl" },
      { key: "escalation_rate", label: "Eskalationsquote", unit: "%" },
      { key: "source_coverage", label: "Antworten mit Quellen", unit: "%" },
    ],
    capabilities: [
      {
        key: "answer-drafting",
        name: "Antwort-Entwürfe",
        description: "Erstellt quellenbasierte Antwortentwürfe.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "medium",
        requiredTools: ["tickets.read", "knowledge.search", "email.draft"],
      },
      {
        key: "auto-answer",
        name: "Automatische Antwort",
        description: "Beantwortet klar gedeckte Standardfragen automatisch.",
        defaultAutomationLevel: 3,
        // Versand nach außen bleibt freigabepflichtig (Spec §4.11).
        maxAutomationLevel: 3,
        riskLevel: "high",
        requiredTools: ["tickets.write", "email.send", "knowledge.search"],
      },
      {
        key: "uncertainty-escalation",
        name: "Eskalation bei Unsicherheit",
        description: "Übergibt unklare Fälle mit Kontext an Menschen.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tickets.write", "notify.send"],
      },
    ],
    requiredIntegrations: [],
    optionalIntegrations: ["email", "helpdesk"],
    dataRequirements: ["Gepflegte Wissensbasis", "Eskalationsregeln"],
    priceTier: "complex",
    securityLevel: "elevated",
  }),

  defineAgent({
    slug: "knowledge-base",
    personaName: "Sam",
    roleTitle: "Knowledge Base Agent",
    department: "customer-service",
    tagline: "Ihre Hilfe-Artikel bleiben aktuell",
    description:
      "Erkennt wiederkehrende Fragen, schlägt neue Artikel vor, aktualisiert Inhalte nur nach Freigabe und verwaltet Quellen und Versionen.",
    responsibilities: [
      "Wiederkehrende Fragen erkennen",
      "Neue Wissensartikel vorschlagen",
      "Inhalte nach Freigabe aktualisieren",
      "Quellen und Versionen verwalten",
    ],
    boundaries: [
      "Veröffentlicht nichts ohne Freigabe",
      "Kennzeichnet Quellen jedes Artikels",
    ],
    kpis: [
      { key: "articles_proposed", label: "Vorgeschlagene Artikel", unit: "Anzahl" },
      { key: "gaps_identified", label: "Erkannte Wissenslücken", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "gap-detection",
        name: "Lücken-Erkennung",
        description: "Erkennt häufige Fragen ohne passenden Artikel.",
        defaultAutomationLevel: 1,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tickets.read", "knowledge.search"],
      },
      {
        key: "article-drafting",
        name: "Artikel-Entwürfe",
        description: "Erstellt Artikelentwürfe zur redaktionellen Freigabe.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "medium",
        requiredTools: ["knowledge.search", "knowledge.write"],
      },
    ],
    requiredIntegrations: [],
    optionalIntegrations: ["helpdesk"],
    dataRequirements: ["Supportanfragen-Historie", "Bestehende Wissensbasis"],
    priceTier: "advanced",
  }),

  defineAgent({
    slug: "ticket-routing",
    personaName: "Tara",
    roleTitle: "Ticket Routing Agent",
    department: "customer-service",
    tagline: "Jedes Ticket sofort beim richtigen Team",
    description:
      "Kategorisiert Tickets, priorisiert nach Regeln, weist Teams zu und erkennt doppelte Tickets.",
    responsibilities: [
      "Tickets kategorisieren",
      "Nach Regeln priorisieren",
      "Teams zuweisen",
      "Doppelte Tickets erkennen",
    ],
    boundaries: [
      "Schließt keine Tickets ohne Regel oder Freigabe",
      "Priorisierung folgt ausschließlich definierten Regeln",
    ],
    kpis: [
      { key: "tickets_routed", label: "Zugeordnete Tickets", unit: "Anzahl" },
      { key: "routing_accuracy", label: "Zuordnungsgenauigkeit", unit: "%" },
      { key: "duplicates_merged", label: "Erkannte Dubletten", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "ticket-classification",
        name: "Kategorisierung & Priorisierung",
        description: "Ordnet Tickets Kategorien und Prioritäten zu.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tickets.read", "tickets.write"],
      },
      {
        key: "team-assignment",
        name: "Team-Zuweisung",
        description: "Weist Tickets regelbasiert Teams zu.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tickets.write"],
      },
    ],
    requiredIntegrations: [],
    optionalIntegrations: ["helpdesk", "email"],
    dataRequirements: ["Ticket-Quelle", "Routing-Regeln"],
    priceTier: "simple",
  }),

  defineAgent({
    slug: "escalation",
    personaName: "Bruno",
    roleTitle: "Escalation Agent",
    department: "customer-service",
    tagline: "Kritische Fälle sofort bei den richtigen Menschen",
    description:
      "Erkennt kritische oder emotionale Fälle, eskaliert Beschwerden, Sicherheitsfälle und rechtliche Drohungen und stoppt autonome Antworten bei hohem Risiko.",
    responsibilities: [
      "Kritische oder emotionale Fälle erkennen",
      "Beschwerden, Sicherheitsfälle und rechtliche Drohungen eskalieren",
      "Autonome Antworten bei hohem Risiko stoppen",
    ],
    boundaries: [
      "Antwortet kritischen Fällen niemals selbst",
      "Eskalationswege sind fest definiert und protokolliert",
    ],
    kpis: [
      { key: "escalations", label: "Eskalierte Fälle", unit: "Anzahl" },
      { key: "detection_speed", label: "Erkennungszeit", unit: "Minuten" },
    ],
    capabilities: [
      {
        key: "risk-detection",
        name: "Risiko-Erkennung",
        description: "Erkennt kritische Signale in Anfragen.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tickets.read"],
      },
      {
        key: "escalation-routing",
        name: "Eskalation",
        description: "Eskaliert an definierte Verantwortliche und stoppt Automatik.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "medium",
        requiredTools: ["tickets.write", "notify.send", "agents.pause"],
      },
    ],
    requiredIntegrations: [],
    optionalIntegrations: ["helpdesk"],
    dataRequirements: ["Eskalationsmatrix", "Ticket-Quelle"],
    priceTier: "advanced",
    securityLevel: "elevated",
  }),

  defineAgent({
    slug: "review",
    personaName: "Elif",
    roleTitle: "Review Agent",
    department: "customer-service",
    tagline: "Bewertungen beantwortet, Kritik erkannt",
    description:
      "Sammelt Kundenfeedback, erstellt Antwortentwürfe auf Bewertungen und erkennt wiederkehrende Kritik — ohne Bewertungen zu löschen oder zu manipulieren.",
    responsibilities: [
      "Kundenfeedback und Bewertungen sammeln",
      "Antwortentwürfe erstellen",
      "Wiederkehrende Kritik erkennen",
    ],
    boundaries: [
      "Löscht oder manipuliert keine Bewertungen",
      "Antwortet nur nach Freigabe oder erlaubter Standardregel",
    ],
    kpis: [
      { key: "reviews_processed", label: "Verarbeitete Bewertungen", unit: "Anzahl" },
      { key: "response_rate", label: "Beantwortungsquote", unit: "%" },
    ],
    capabilities: [
      {
        key: "review-collection",
        name: "Feedback-Sammlung",
        description: "Sammelt und kategorisiert eingehendes Feedback.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tickets.read"],
      },
      {
        key: "response-drafting",
        name: "Antwort-Entwürfe",
        description: "Erstellt Antwortentwürfe auf Bewertungen.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "medium",
        requiredTools: ["email.draft"],
      },
    ],
    requiredIntegrations: [],
    dataRequirements: ["Bewertungsquellen (Import oder Weiterleitung)"],
    priceTier: "simple",
  }),

  defineAgent({
    slug: "customer-recovery",
    personaName: "Carla",
    roleTitle: "Customer Recovery Agent",
    department: "customer-service",
    tagline: "Gefährdete Kunden rechtzeitig zurückgewinnen",
    description:
      "Erkennt gefährdete Kunden, erstellt Rückgewinnungsvorschläge unter Berücksichtigung erlaubter Angebote — versendet nichts ohne entsprechende Berechtigung.",
    responsibilities: [
      "Gefährdete Kunden anhand von Signalen erkennen",
      "Rückgewinnungsvorschläge erstellen",
      "Erlaubte Angebote berücksichtigen",
    ],
    boundaries: [
      "Versendet nichts ohne entsprechende Berechtigung",
      "Bietet nur freigegebene Konditionen an",
    ],
    kpis: [
      { key: "at_risk_detected", label: "Erkannte gefährdete Kunden", unit: "Anzahl" },
      { key: "recovered", label: "Zurückgewonnene Kunden", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "churn-detection",
        name: "Gefährdungs-Erkennung",
        description: "Erkennt Abwanderungssignale.",
        defaultAutomationLevel: 1,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["crm.read", "tickets.read"],
      },
      {
        key: "recovery-drafting",
        name: "Rückgewinnungs-Vorschläge",
        description: "Erstellt Vorschläge und Nachrichtenentwürfe.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "high",
        requiredTools: ["crm.read", "email.draft"],
      },
    ],
    requiredIntegrations: ["crm"],
    dataRequirements: ["Kundendaten mit Aktivitätssignalen", "Erlaubte Angebote"],
    priceTier: "advanced",
  }),

  defineAgent({
    slug: "complaint",
    personaName: "Henry",
    roleTitle: "Complaint Agent",
    department: "customer-service",
    tagline: "Reklamationen strukturiert aufbereitet",
    description:
      "Erfasst Reklamationen, sammelt erforderliche Daten, erstellt Fallzusammenfassungen und schlägt nächste Schritte vor — ohne rechtlich bindende Anerkenntnisse.",
    responsibilities: [
      "Reklamationen erfassen",
      "Erforderliche Daten sammeln",
      "Fallzusammenfassungen erstellen",
      "Nächste Schritte vorschlagen",
    ],
    boundaries: [
      "Trifft keine rechtlich bindenden Anerkenntnisse",
      "Zusagen erfordern menschliche Freigabe",
    ],
    kpis: [
      { key: "complaints_processed", label: "Erfasste Reklamationen", unit: "Anzahl" },
      { key: "resolution_time", label: "Bearbeitungszeit", unit: "Tage" },
    ],
    capabilities: [
      {
        key: "complaint-intake",
        name: "Erfassung",
        description: "Erfasst Reklamationen strukturiert mit allen Pflichtdaten.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "medium",
        requiredTools: ["tickets.read", "tickets.write"],
      },
      {
        key: "case-summary",
        name: "Fallzusammenfassung",
        description: "Erstellt Zusammenfassungen mit Vorschlag nächster Schritte.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "medium",
        requiredTools: ["tickets.read"],
      },
    ],
    requiredIntegrations: [],
    optionalIntegrations: ["helpdesk", "email"],
    dataRequirements: ["Reklamationsprozess", "Ticket-Quelle"],
    priceTier: "advanced",
  }),

  defineAgent({
    slug: "quality",
    personaName: "Aylin",
    roleTitle: "Quality Agent",
    department: "customer-service",
    tagline: "Support-Qualität messbar verbessern",
    description:
      "Analysiert Supportfälle, bewertet Antworten nach definierten Kriterien, erkennt Wissenslücken und erstellt Coaching-Vorschläge.",
    responsibilities: [
      "Supportfälle analysieren",
      "Antworten nach definierten Kriterien bewerten",
      "Wissenslücken erkennen",
      "Coaching-Vorschläge erstellen",
    ],
    boundaries: [
      "Bewertet Antworten, nicht Menschen — keine Leistungsbeurteilung von Mitarbeitenden",
      "Kriterien sind transparent und konfigurierbar",
    ],
    kpis: [
      { key: "cases_analyzed", label: "Analysierte Fälle", unit: "Anzahl" },
      { key: "gaps_found", label: "Erkannte Wissenslücken", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "case-analysis",
        name: "Fall-Analyse",
        description: "Bewertet Supportantworten nach Qualitätsrubrik.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tickets.read", "reports.generate"],
      },
      {
        key: "coaching-suggestions",
        name: "Coaching-Vorschläge",
        description: "Erstellt Verbesserungs- und Schulungsvorschläge.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "low",
        requiredTools: ["tickets.read", "knowledge.search"],
      },
    ],
    requiredIntegrations: [],
    dataRequirements: ["Supportfall-Historie", "Qualitätskriterien"],
    priceTier: "advanced",
  }),
];
