import { defineAgent } from "./helpers";

/**
 * AI Finance Operations: ausschließlich operative Unterstützung — ersetzt
 * keine Buchhaltung, Steuerberatung, Abschlussprüfung oder Finanzberatung.
 */
export const financeAgents = [
  defineAgent({
    slug: "invoice-intake",
    personaName: "Klara",
    roleTitle: "Invoice Intake Agent",
    department: "finance",
    tagline: "Rechnungseingang ohne Abtippen",
    description:
      "Erkennt eingehende Rechnungen, extrahiert Daten, prüft Pflichtfelder, erkennt mögliche Dubletten, gleicht Bestellungen und Lieferanten ab und übergibt Unklarheiten an Menschen.",
    responsibilities: [
      "Rechnungen erkennen und Daten extrahieren",
      "Pflichtfelder prüfen (z. B. Rechnungsnummer, Betrag, USt.)",
      "Mögliche Dubletten erkennen",
      "Bestellungen und Lieferanten abgleichen",
      "Unklarheiten an Menschen übergeben",
    ],
    boundaries: [
      "Löst keine Zahlungen aus und verbucht nichts",
      "Trifft keine steuerliche Bewertung",
      "Bei Unsicherheit wird immer eine Prüfaufgabe erstellt",
    ],
    kpis: [
      { key: "invoices_processed", label: "Verarbeitete Rechnungen", unit: "Anzahl" },
      { key: "extraction_accuracy", label: "Extraktionsgenauigkeit", unit: "%" },
      { key: "duplicates_flagged", label: "Erkannte Dubletten", unit: "Anzahl" },
      { key: "manual_review_rate", label: "Übergaben an Menschen", unit: "%" },
    ],
    capabilities: [
      {
        key: "invoice-extraction",
        name: "Datenextraktion",
        description: "Extrahiert strukturierte Daten aus Rechnungen.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "medium",
        requiredTools: ["documents.read", "finance.read", "finance.write", "tasks.write"],
      },
      {
        key: "field-check",
        name: "Pflichtfeld-Prüfung",
        description: "Prüft Rechnungen auf fehlende Pflichtangaben.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["documents.read", "finance.read", "finance.write", "tasks.write"],
      },
      {
        key: "duplicate-check",
        name: "Dubletten-Abgleich",
        description: "Gleicht neue Rechnungen gegen den Bestand ab.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["finance.read"],
      },
      {
        key: "review-task",
        name: "Prüfaufgaben",
        description: "Erstellt Prüfaufgaben bei Unklarheiten.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tasks.write"],
      },
    ],
    requiredIntegrations: [],
    optionalIntegrations: ["email", "accounting", "csv"],
    dataRequirements: ["Rechnungen (Upload, E-Mail oder Dateispeicher)", "Lieferantenstamm (optional)"],
    priceTier: "complex",
    securityLevel: "elevated",
    implementationDepth: "deep",
  }),

  defineAgent({
    slug: "payment-monitoring",
    personaName: "Jan",
    roleTitle: "Payment Monitoring Agent",
    department: "finance",
    tagline: "Offene Posten immer im Blick",
    description:
      "Überwacht importierte Zahlungseingänge, ordnet Zahlungen nach Regeln zu und meldet offene Posten — ohne Bankdaten zu verändern oder Zahlungen auszulösen.",
    responsibilities: [
      "Importierte Zahlungseingänge überwachen",
      "Zahlungen regelbasiert Rechnungen zuordnen",
      "Offene Posten melden",
    ],
    boundaries: [
      "Verändert keine Bankdaten",
      "Löst keine Zahlungen aus",
      "Unklare Zuordnungen werden zur manuellen Prüfung markiert",
    ],
    kpis: [
      { key: "payments_matched", label: "Zugeordnete Zahlungen", unit: "%" },
      { key: "open_items", label: "Gemeldete offene Posten", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "payment-matching",
        name: "Zahlungszuordnung",
        description: "Ordnet Zahlungseingänge Rechnungen zu.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "medium",
        requiredTools: ["finance.read", "finance.write"],
      },
      {
        key: "open-item-report",
        name: "Offene-Posten-Meldung",
        description: "Meldet überfällige und offene Posten.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["finance.read", "notify.send"],
      },
    ],
    requiredIntegrations: ["csv"],
    optionalIntegrations: ["accounting"],
    dataRequirements: ["Zahlungsimport (CSV oder Buchhaltungs-Integration)", "Offene-Posten-Liste"],
    priceTier: "advanced",
    securityLevel: "elevated",
  }),

  defineAgent({
    slug: "dunning-draft",
    personaName: "Eva",
    roleTitle: "Dunning Draft Agent",
    department: "finance",
    tagline: "Mahnentwürfe nach Ihren Regeln",
    description:
      "Erkennt überfällige Forderungen, erstellt Mahnentwürfe nach hinterlegten Regeln und berücksichtigt Sperrvermerke und Streitfälle.",
    responsibilities: [
      "Überfällige Forderungen erkennen",
      "Mahnentwürfe nach hinterlegten Regeln und Stufen erstellen",
      "Sperrvermerke und Streitfälle berücksichtigen",
    ],
    boundaries: [
      "Versendet nur bei Freigabe oder ausdrücklich erlaubter Standardregel",
      "Keine Mahnungen bei Sperrvermerk oder offenem Streitfall",
      "Keine rechtliche Bewertung von Forderungen",
    ],
    kpis: [
      { key: "dunning_drafts", label: "Erstellte Mahnentwürfe", unit: "Anzahl" },
      { key: "collected_amount", label: "Beglichene überfällige Beträge", unit: "€" },
    ],
    capabilities: [
      {
        key: "overdue-detection",
        name: "Überfälligkeits-Erkennung",
        description: "Erkennt überfällige Forderungen nach Fristen.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["finance.read"],
      },
      {
        key: "dunning-drafting",
        name: "Mahnentwürfe",
        description: "Erstellt stufengerechte Mahnentwürfe zur Freigabe.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 3,
        riskLevel: "high",
        requiredTools: ["finance.read", "email.draft"],
      },
    ],
    requiredIntegrations: [],
    optionalIntegrations: ["email", "accounting"],
    dataRequirements: ["Offene-Posten-Liste", "Mahnstufen-Regeln", "Sperrvermerke"],
    priceTier: "advanced",
    securityLevel: "elevated",
  }),

  defineAgent({
    slug: "expense",
    personaName: "Max",
    roleTitle: "Expense Agent",
    department: "finance",
    tagline: "Spesen kategorisiert und richtlinienkonform",
    description:
      "Kategorisiert Ausgaben, prüft Belegvollständigkeit, erkennt Richtlinienabweichungen und fordert fehlende Angaben an — ohne steuerliche Endbewertung.",
    responsibilities: [
      "Ausgaben kategorisieren",
      "Belegvollständigkeit prüfen",
      "Richtlinienabweichungen erkennen",
      "Fehlende Angaben anfordern",
    ],
    boundaries: [
      "Trifft keine steuerliche Endbewertung",
      "Genehmigt keine Ausgaben — das bleibt beim Menschen",
    ],
    kpis: [
      { key: "expenses_processed", label: "Verarbeitete Ausgaben", unit: "Anzahl" },
      { key: "policy_violations", label: "Erkannte Abweichungen", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "expense-classification",
        name: "Kategorisierung",
        description: "Ordnet Ausgaben Kategorien und Kostenstellen zu.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["finance.read", "finance.write", "documents.read"],
      },
      {
        key: "policy-check",
        name: "Richtlinien-Prüfung",
        description: "Prüft Ausgaben gegen die Spesenrichtlinie.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["finance.read"],
      },
    ],
    requiredIntegrations: [],
    optionalIntegrations: ["accounting", "csv"],
    dataRequirements: ["Spesenrichtlinie", "Belege"],
    priceTier: "simple",
  }),

  defineAgent({
    slug: "cashflow-monitoring",
    personaName: "Rosa",
    roleTitle: "Cashflow Monitoring Agent",
    department: "finance",
    tagline: "Operative Liquidität transparent gemacht",
    description:
      "Erstellt operative Liquiditätsübersichten aus vorhandenen Daten, zeigt Annahmen und Unsicherheiten und meldet auffällige Entwicklungen — keine Anlageberatung.",
    responsibilities: [
      "Operative Liquiditätsübersichten erstellen",
      "Nur vorhandene Daten nutzen, Annahmen ausweisen",
      "Auffällige Entwicklungen melden",
    ],
    boundaries: [
      "Erteilt keine Anlage- oder Finanzierungsberatung",
      "Weist Unsicherheiten und Datenlücken immer aus",
      "Prognosen sind klar als Schätzungen gekennzeichnet",
    ],
    kpis: [
      { key: "overviews_created", label: "Erstellte Übersichten", unit: "Anzahl" },
      { key: "anomalies_flagged", label: "Gemeldete Auffälligkeiten", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "liquidity-overview",
        name: "Liquiditätsübersicht",
        description: "Erstellt Übersichten aus Ein- und Auszahlungsdaten.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 4,
        riskLevel: "medium",
        requiredTools: ["finance.read", "reports.generate"],
      },
      {
        key: "anomaly-alert",
        name: "Auffälligkeits-Meldung",
        description: "Meldet ungewöhnliche Entwicklungen.",
        defaultAutomationLevel: 1,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["finance.read", "notify.send"],
      },
    ],
    requiredIntegrations: ["csv"],
    optionalIntegrations: ["accounting"],
    dataRequirements: ["Zahlungsdaten (Import)", "Offene Forderungen und Verbindlichkeiten"],
    priceTier: "complex",
    securityLevel: "elevated",
  }),

  defineAgent({
    slug: "monthly-reporting",
    personaName: "Leo",
    roleTitle: "Monthly Reporting Agent",
    department: "finance",
    tagline: "Managementberichte mit nachvollziehbaren Quellen",
    description:
      "Erstellt Managementberichte, vergleicht Perioden, erkennt Abweichungen, verlinkt Datenquellen und kennzeichnet unvollständige Daten.",
    responsibilities: [
      "Monatliche Managementberichte erstellen",
      "Perioden vergleichen und Abweichungen erkennen",
      "Datenquellen verlinken",
      "Unvollständige Daten kennzeichnen",
    ],
    boundaries: [
      "Ersetzt keinen Jahresabschluss und keine Steuerberatung",
      "Jede Kennzahl ist auf ihre Quelle zurückführbar",
    ],
    kpis: [
      { key: "reports_created", label: "Erstellte Berichte", unit: "Anzahl" },
      { key: "variances_flagged", label: "Erkannte Abweichungen", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "report-generation",
        name: "Berichtserstellung",
        description: "Erstellt Monatsberichte mit Periodenvergleich.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["finance.read", "reports.generate"],
      },
      {
        key: "variance-analysis",
        name: "Abweichungsanalyse",
        description: "Erkennt und erläutert Abweichungen zwischen Perioden.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["finance.read"],
      },
    ],
    requiredIntegrations: ["csv"],
    optionalIntegrations: ["accounting"],
    dataRequirements: ["Finanzdaten je Periode (Import oder Integration)"],
    priceTier: "advanced",
  }),

  defineAgent({
    slug: "receipt",
    personaName: "Anna",
    roleTitle: "Receipt Agent",
    department: "finance",
    tagline: "Belege erfasst, zugeordnet, vollständig",
    description:
      "Verarbeitet Belege, liest Felder aus, erkennt Dubletten, ordnet Projekte und Kostenstellen nach Regeln zu und fordert bei Unsicherheit eine Freigabe an.",
    responsibilities: [
      "Belege verarbeiten und Felder auslesen",
      "Dubletten erkennen",
      "Projekte und Kostenstellen regelbasiert zuordnen",
      "Bei Unsicherheit Freigabe anfordern",
    ],
    boundaries: [
      "Verbucht nichts eigenständig",
      "Unsichere Zuordnungen gehen immer in die Freigabe",
    ],
    kpis: [
      { key: "receipts_processed", label: "Verarbeitete Belege", unit: "Anzahl" },
      { key: "auto_assigned", label: "Automatisch zugeordnet", unit: "%" },
    ],
    capabilities: [
      {
        key: "receipt-extraction",
        name: "Beleg-Extraktion",
        description: "Liest Felder aus Belegen aus.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["documents.read", "finance.write"],
      },
      {
        key: "cost-assignment",
        name: "Kostenstellen-Zuordnung",
        description: "Ordnet Belege Projekten und Kostenstellen zu.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "medium",
        requiredTools: ["finance.read", "finance.write"],
      },
    ],
    requiredIntegrations: [],
    optionalIntegrations: ["accounting", "files"],
    dataRequirements: ["Belege (Upload)", "Kostenstellenplan (optional)"],
    priceTier: "simple",
  }),

  defineAgent({
    slug: "budget-monitoring",
    personaName: "Felix",
    roleTitle: "Budget Monitoring Agent",
    department: "finance",
    tagline: "Budgets im Griff, bevor sie überschritten sind",
    description:
      "Vergleicht Ist-Werte mit Budgets, erkennt Überschreitungen und benachrichtigt Verantwortliche — ohne manipulative Buchungsvorschläge.",
    responsibilities: [
      "Ist-Werte mit Budgets vergleichen",
      "Überschreitungen und Trends erkennen",
      "Verantwortliche benachrichtigen",
    ],
    boundaries: [
      "Schlägt keine manipulativen Buchungen vor",
      "Ändert keine Budgets",
    ],
    kpis: [
      { key: "budgets_monitored", label: "Überwachte Budgets", unit: "Anzahl" },
      { key: "overruns_detected", label: "Erkannte Überschreitungen", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "budget-comparison",
        name: "Budget-Vergleich",
        description: "Vergleicht Ist-Werte gegen Budgetpläne.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["finance.read", "reports.generate"],
      },
      {
        key: "overrun-alert",
        name: "Überschreitungs-Warnung",
        description: "Warnt Verantwortliche bei drohender Überschreitung.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["finance.read", "notify.send"],
      },
    ],
    requiredIntegrations: ["csv"],
    dataRequirements: ["Budgetplan", "Ist-Daten (Import)"],
    priceTier: "advanced",
  }),
];
