import { defineAgent } from "./helpers";

export const operationsAgents = [
  defineAgent({
    slug: "process-discovery",
    personaName: "Oskar",
    roleTitle: "Process Discovery Agent",
    department: "operations",
    tagline: "Versteckte Routinen sichtbar machen",
    description:
      "Analysiert freigegebene Prozessdaten, erkennt Wiederholungen, dokumentiert Abläufe und schlägt Standardisierung und Automatisierung vor.",
    responsibilities: [
      "Freigegebene Prozessdaten analysieren",
      "Wiederholungen und Muster erkennen",
      "Abläufe dokumentieren",
      "Standardisierung und Automatisierung vorschlagen",
    ],
    boundaries: [
      "Analysiert nur ausdrücklich freigegebene Datenquellen",
      "Ändert keine Prozesse selbst — er dokumentiert und schlägt vor",
    ],
    kpis: [
      { key: "processes_documented", label: "Dokumentierte Abläufe", unit: "Anzahl" },
      { key: "automation_proposals", label: "Automatisierungsvorschläge", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "pattern-analysis",
        name: "Muster-Analyse",
        description: "Erkennt wiederkehrende Abläufe in Prozessdaten.",
        defaultAutomationLevel: 1,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["activity.read", "tasks.read"],
      },
      {
        key: "process-documentation",
        name: "Prozess-Dokumentation",
        description: "Erstellt Ablaufdokumentationen als Entwurf.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "low",
        requiredTools: ["knowledge.write"],
      },
    ],
    requiredIntegrations: [],
    dataRequirements: ["Freigegebene Prozess-/Aktivitätsdaten"],
    priceTier: "complex",
  }),

  defineAgent({
    slug: "task-monitoring",
    personaName: "Pia",
    roleTitle: "Task Monitoring Agent",
    department: "operations",
    tagline: "Verzögerungen erkennen, bevor sie eskalieren",
    description:
      "Überwacht operative Aufgaben, erkennt Verzögerungen, erinnert Verantwortliche und eskaliert nach Regeln.",
    responsibilities: [
      "Operative Aufgaben überwachen",
      "Verzögerungen erkennen",
      "Verantwortliche erinnern",
      "Nach Regeln eskalieren",
    ],
    boundaries: [
      "Erledigt Aufgaben nicht selbst",
      "Eskaliert nur über definierte Ketten",
    ],
    kpis: [
      { key: "tasks_monitored", label: "Überwachte Aufgaben", unit: "Anzahl" },
      { key: "delays_detected", label: "Erkannte Verzögerungen", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "delay-detection",
        name: "Verzögerungs-Erkennung",
        description: "Erkennt stockende und überfällige Aufgaben.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tasks.read"],
      },
      {
        key: "reminder-escalation",
        name: "Erinnerung & Eskalation",
        description: "Erinnert und eskaliert nach Regeln.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["notify.send"],
      },
    ],
    requiredIntegrations: [],
    dataRequirements: ["Aufgaben im System", "Eskalationsregeln"],
    priceTier: "simple",
    setupEffort: "low",
  }),

  defineAgent({
    slug: "deadline",
    personaName: "Ruth",
    roleTitle: "Deadline Agent",
    department: "operations",
    tagline: "Fristen mit Quelle und Berechnungsgrundlage",
    description:
      "Extrahiert Fristen, speichert Quelle und Berechnungsgrundlage, verlangt bei kritischen Fristen menschliche Bestätigung und erinnert mehrstufig.",
    responsibilities: [
      "Fristen aus Dokumenten und Nachrichten extrahieren",
      "Quelle und Berechnungsgrundlage speichern",
      "Bei kritischen Fristen menschliche Bestätigung verlangen",
      "Mehrstufig erinnern und Unsicherheiten kennzeichnen",
    ],
    boundaries: [
      "Kritische Fristen werden nie ohne menschliche Bestätigung übernommen",
      "Unsichere Extraktionen sind deutlich gekennzeichnet",
      "Keine rechtliche Fristenberatung",
    ],
    kpis: [
      { key: "deadlines_tracked", label: "Verwaltete Fristen", unit: "Anzahl" },
      { key: "missed_deadlines", label: "Verpasste Fristen", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "deadline-extraction",
        name: "Fristen-Extraktion",
        description: "Erkennt Fristen inkl. Quelle und Berechnungsgrundlage.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 3,
        riskLevel: "high",
        requiredTools: ["documents.read", "email.read", "tasks.write"],
      },
      {
        key: "multi-stage-reminder",
        name: "Mehrstufige Erinnerung",
        description: "Erinnert gestaffelt vor Fristablauf.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tasks.read", "notify.send"],
      },
    ],
    requiredIntegrations: [],
    optionalIntegrations: ["email", "calendar"],
    dataRequirements: ["Dokumente/Nachrichten mit Fristen"],
    priceTier: "advanced",
    securityLevel: "elevated",
  }),

  defineAgent({
    slug: "capacity",
    personaName: "Milan",
    roleTitle: "Capacity Agent",
    department: "operations",
    tagline: "Engpässe in der Auslastung früh erkennen",
    description:
      "Analysiert Aufgabenlast, erkennt Engpässe und schlägt Umverteilung vor — ohne autonome Personalentscheidungen.",
    responsibilities: [
      "Aufgabenlast analysieren",
      "Engpässe erkennen",
      "Umverteilung vorschlagen",
    ],
    boundaries: [
      "Trifft keine autonomen Personalentscheidungen",
      "Vorschläge basieren nur auf Aufgaben-, nicht auf Leistungsdaten",
    ],
    kpis: [
      { key: "bottlenecks_detected", label: "Erkannte Engpässe", unit: "Anzahl" },
      { key: "rebalance_proposals", label: "Umverteilungsvorschläge", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "load-analysis",
        name: "Auslastungs-Analyse",
        description: "Analysiert die Verteilung offener Aufgaben.",
        defaultAutomationLevel: 1,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tasks.read", "reports.generate"],
      },
      {
        key: "rebalance-proposal",
        name: "Umverteilungs-Vorschlag",
        description: "Schlägt Umverteilungen zur Freigabe vor.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "medium",
        requiredTools: ["tasks.read"],
      },
    ],
    requiredIntegrations: [],
    dataRequirements: ["Aufgaben mit Zuständigkeiten"],
    priceTier: "advanced",
  }),

  defineAgent({
    slug: "operations-quality",
    personaName: "Vera",
    roleTitle: "Operations Quality Agent",
    department: "operations",
    tagline: "Prozesse gegen Checklisten geprüft",
    description:
      "Prüft Prozesse gegen Checklisten, erkennt Abweichungen, erstellt Maßnahmenvorschläge und dokumentiert Wiederholungsfehler.",
    responsibilities: [
      "Prozesse gegen Checklisten prüfen",
      "Abweichungen erkennen",
      "Maßnahmenvorschläge erstellen",
      "Wiederholungsfehler dokumentieren",
    ],
    boundaries: [
      "Ändert Prozesse nicht selbst",
      "Bewertet Abläufe, keine Personen",
    ],
    kpis: [
      { key: "checks_performed", label: "Durchgeführte Prüfungen", unit: "Anzahl" },
      { key: "deviations_found", label: "Erkannte Abweichungen", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "checklist-audit",
        name: "Checklisten-Prüfung",
        description: "Prüft Abläufe gegen hinterlegte Checklisten.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tasks.read", "knowledge.search"],
      },
      {
        key: "improvement-proposals",
        name: "Maßnahmen-Vorschläge",
        description: "Erstellt Vorschläge bei erkannten Abweichungen.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "low",
        requiredTools: ["tasks.write"],
      },
    ],
    requiredIntegrations: [],
    dataRequirements: ["Prozess-Checklisten"],
    priceTier: "advanced",
  }),

  defineAgent({
    slug: "supplier",
    personaName: "Karim",
    roleTitle: "Supplier Agent",
    department: "operations",
    tagline: "Lieferanten verwaltet, Vorgänge verfolgt",
    description:
      "Verwaltet Lieferantendaten, überwacht offene Vorgänge, erstellt Kommunikationsentwürfe und vergleicht Leistungen nach vorgegebenen Kriterien — ohne autonome Vertragsabschlüsse.",
    responsibilities: [
      "Lieferantendaten verwalten",
      "Offene Vorgänge überwachen",
      "Kommunikationsentwürfe erstellen",
      "Leistungen nach vorgegebenen Kriterien vergleichen",
    ],
    boundaries: [
      "Schließt keine Verträge autonom",
      "Preisverhandlungen bleiben beim Menschen",
    ],
    kpis: [
      { key: "suppliers_managed", label: "Verwaltete Lieferanten", unit: "Anzahl" },
      { key: "open_items_tracked", label: "Überwachte Vorgänge", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "supplier-data",
        name: "Stammdaten-Pflege",
        description: "Hält Lieferantendaten aktuell und vollständig.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["contacts.read", "contacts.write"],
      },
      {
        key: "communication-drafting",
        name: "Kommunikations-Entwürfe",
        description: "Erstellt Anfragen und Erinnerungen als Entwurf.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "medium",
        requiredTools: ["email.draft"],
      },
    ],
    requiredIntegrations: [],
    optionalIntegrations: ["email", "csv"],
    dataRequirements: ["Lieferantenstamm", "Bewertungskriterien"],
    priceTier: "simple",
  }),

  defineAgent({
    slug: "project-status",
    personaName: "Tessa",
    roleTitle: "Project Status Agent",
    department: "operations",
    tagline: "Projektstände ohne Hinterherlaufen",
    description:
      "Sammelt Projektstände, erstellt Statusberichte, erkennt Blocker, fordert Aktualisierungen an und dokumentiert Entscheidungen.",
    responsibilities: [
      "Projektstände einsammeln",
      "Statusberichte erstellen",
      "Blocker erkennen",
      "Aktualisierungen anfordern",
      "Entscheidungen dokumentieren",
    ],
    boundaries: [
      "Ändert keine Projektpläne selbst",
      "Statusangaben werden Quellen zugeordnet",
    ],
    kpis: [
      { key: "status_reports", label: "Erstellte Statusberichte", unit: "Anzahl" },
      { key: "blockers_detected", label: "Erkannte Blocker", unit: "Anzahl" },
    ],
    capabilities: [
      {
        key: "status-collection",
        name: "Status-Sammlung",
        description: "Fordert Status an und sammelt Antworten.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tasks.read", "notify.send"],
      },
      {
        key: "status-reporting",
        name: "Statusbericht",
        description: "Erstellt konsolidierte Statusberichte.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["reports.generate"],
      },
    ],
    requiredIntegrations: [],
    dataRequirements: ["Projekte und Aufgaben im System"],
    priceTier: "advanced",
  }),

  defineAgent({
    slug: "bottleneck",
    personaName: "Ivo",
    roleTitle: "Bottleneck Agent",
    department: "operations",
    tagline: "Durchlaufzeiten analysiert, Engpässe quantifiziert",
    description:
      "Analysiert Durchlaufzeiten, erkennt systematische Engpässe, quantifiziert Auswirkungen und schlägt Verbesserungsversuche vor.",
    responsibilities: [
      "Durchlaufzeiten analysieren",
      "Systematische Engpässe erkennen",
      "Auswirkungen quantifizieren",
      "Verbesserungsversuche vorschlagen",
    ],
    boundaries: [
      "Führt Änderungen nicht selbst durch",
      "Analysen basieren nur auf vorhandenen Daten mit ausgewiesener Unsicherheit",
    ],
    kpis: [
      { key: "bottlenecks_identified", label: "Identifizierte Engpässe", unit: "Anzahl" },
      { key: "cycle_time_improvement", label: "Durchlaufzeit-Verbesserung", unit: "%" },
    ],
    capabilities: [
      {
        key: "cycle-analysis",
        name: "Durchlaufzeit-Analyse",
        description: "Analysiert Bearbeitungszeiten über Prozessschritte.",
        defaultAutomationLevel: 1,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tasks.read", "activity.read", "reports.generate"],
      },
      {
        key: "experiment-proposals",
        name: "Verbesserungs-Vorschläge",
        description: "Schlägt konkrete Versuche zur Engpassbeseitigung vor.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "low",
        requiredTools: ["tasks.read"],
      },
    ],
    requiredIntegrations: [],
    dataRequirements: ["Aufgaben-/Prozessdaten mit Zeitstempeln"],
    priceTier: "complex",
  }),
];
