import { defineAgent } from "./helpers";

export const salesAgents = [
  defineAgent({
    slug: "lead-research",
    personaName: "Jonas",
    roleTitle: "Lead Research Agent",
    department: "sales",
    tagline: "Recherchiert Zielkunden, die wirklich zu Ihnen passen",
    description:
      "Analysiert Ihre Zielkundenprofile, verarbeitet erlaubte Datenquellen, erstellt Zielkundenlisten mit öffentlich verfügbaren Unternehmensinformationen und bewertet den ICP-Fit.",
    responsibilities: [
      "Definierte Zielkundenprofile (ICP) analysieren",
      "Erlaubte Datenquellen verarbeiten und Zielkundenlisten erstellen",
      "Öffentlich verfügbare Unternehmensinformationen ergänzen",
      "ICP-Fit bewerten und mögliche Kontaktanlässe erkennen",
      "Recherche-Zusammenfassungen mit Quellenangaben erstellen",
    ],
    boundaries: [
      "Keine rechtswidrige Datenerhebung",
      "Kein Umgehen technischer Schutzmaßnahmen",
      "Keine automatisierte Massenansprache ohne zulässige Grundlage",
      "Quellen und Datenherkunft werden immer dokumentiert",
    ],
    kpis: [
      { key: "companies_researched", label: "Recherchierte Unternehmen", unit: "Anzahl" },
      { key: "qualified_targets", label: "Qualifizierte Zielkunden", unit: "Anzahl" },
      { key: "data_completeness", label: "Datenvollständigkeit", unit: "%" },
      { key: "accepted_recommendations", label: "Akzeptierte Empfehlungen", unit: "%" },
    ],
    capabilities: [
      {
        key: "icp-research",
        name: "Zielkundenrecherche",
        description: "Erstellt und ergänzt Zielkundenlisten anhand des ICP.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["crm.read", "web.research", "contacts.write"],
      },
      {
        key: "icp-scoring",
        name: "ICP-Bewertung",
        description: "Bewertet Unternehmen nach Passung, Potenzial und Anlass.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["crm.read"],
      },
      {
        key: "research-summary",
        name: "Recherche-Zusammenfassung",
        description: "Erstellt quellenbasierte Kurzprofile je Zielkunde.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["crm.read", "web.research"],
      },
    ],
    requiredIntegrations: ["crm"],
    optionalIntegrations: ["csv"],
    dataRequirements: ["Zielkundenprofil (ICP)", "CRM- oder CSV-Kontaktbasis"],
    priceTier: "advanced",
  }),

  defineAgent({
    slug: "lead-qualification",
    personaName: "Mila",
    roleTitle: "Lead Qualification Agent",
    department: "sales",
    tagline: "Bewertet und priorisiert eingehende Leads",
    description:
      "Verarbeitet eingehende Leads, stellt freigegebene Qualifizierungsfragen, bewertet Bedarf, Eignung, Dringlichkeit und Potenzial und erzeugt Übergabezusammenfassungen für den Vertrieb.",
    responsibilities: [
      "Eingehende Leads verarbeiten und anreichern",
      "Freigegebene Qualifizierungsfragen stellen",
      "Bedarf, Eignung, Dringlichkeit und Potenzial bewerten",
      "Leads priorisieren",
      "Übergabezusammenfassungen für den Vertrieb erzeugen",
    ],
    boundaries: [
      "Keine Zusagen oder Preisauskünfte ohne hinterlegte Regeln",
      "Antwortet nur über freigegebene Kanäle und Vorlagen",
      "Lehnt Leads nicht endgültig ab — die Entscheidung bleibt beim Vertrieb",
    ],
    kpis: [
      { key: "qualified_leads", label: "Qualifizierte Leads", unit: "Anzahl" },
      { key: "response_time", label: "Reaktionszeit", unit: "Minuten" },
      { key: "sales_acceptance", label: "Akzeptanzquote Vertrieb", unit: "%" },
      { key: "meeting_rate", label: "Terminquote", unit: "%" },
    ],
    capabilities: [
      {
        key: "lead-scoring",
        name: "Lead-Bewertung",
        description: "Bewertet Leads nach Bedarf, Eignung, Dringlichkeit, Potenzial.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["crm.read", "crm.write"],
      },
      {
        key: "qualification-questions",
        name: "Qualifizierungsfragen",
        description: "Entwirft Rückfragen an Leads auf Basis freigegebener Fragenkataloge.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "medium",
        requiredTools: ["crm.read", "email.draft"],
      },
      {
        key: "handover-summary",
        name: "Übergabezusammenfassung",
        description: "Erstellt kompakte Übergaben mit allen relevanten Informationen.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["crm.read"],
      },
    ],
    requiredIntegrations: ["crm"],
    optionalIntegrations: ["email"],
    dataRequirements: ["Lead-Quelle (CRM, Formular oder CSV)", "Qualifizierungskriterien"],
    priceTier: "advanced",
  }),

  defineAgent({
    slug: "outreach-draft",
    personaName: "Lena",
    roleTitle: "Outreach Drafting Agent",
    department: "sales",
    tagline: "Personalisierte Ansprache-Entwürfe in Ihrer Tonalität",
    description:
      "Erstellt personalisierte Ansprache-Entwürfe und Sequenzen auf Basis Ihrer Tonalität und Angebotsdaten, erzeugt Varianten und stoppt Sequenzen automatisch bei Antworten.",
    responsibilities: [
      "Personalisierte Entwürfe für die Erstansprache erstellen",
      "Tonalität und Angebotsdaten des Unternehmens nutzen",
      "Mehrstufige Sequenzen und Varianten entwerfen",
      "Antworten erkennen und weitere Schritte stoppen",
    ],
    boundaries: [
      "Arbeitet standardmäßig nur im Entwurfs- oder Freigabemodus",
      "Compliance-Hinweise zu Datenschutz, Wettbewerbsrecht und Opt-out werden angezeigt",
      "Kein Versand ohne ausdrückliche Freigabe oder explizit erlaubte Regel",
      "Keine Ansprache von Kontakten mit Opt-out oder Sperrvermerk",
    ],
    kpis: [
      { key: "drafts_created", label: "Erstellte Entwürfe", unit: "Anzahl" },
      { key: "drafts_approved", label: "Freigegebene Entwürfe", unit: "%" },
      { key: "reply_rate", label: "Antwortquote", unit: "%" },
    ],
    capabilities: [
      {
        key: "outreach-drafting",
        name: "Ansprache-Entwürfe",
        description: "Erstellt personalisierte Nachrichtenentwürfe und Varianten.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "medium",
        requiredTools: ["crm.read", "email.draft"],
      },
      {
        key: "sequence-design",
        name: "Sequenz-Entwurf",
        description: "Entwirft mehrstufige Follow-up-Sequenzen mit Stopp-Regeln.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "medium",
        requiredTools: ["crm.read", "email.draft"],
      },
      {
        key: "reply-detection",
        name: "Antwort-Erkennung",
        description: "Erkennt Antworten und stoppt geplante Folgeschritte.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["email.read"],
      },
    ],
    requiredIntegrations: ["email", "crm"],
    dataRequirements: ["Tonalitäts-Leitfaden", "Angebots-/Produktdaten", "Opt-out-Liste"],
    priceTier: "advanced",
    securityLevel: "elevated",
  }),

  defineAgent({
    slug: "follow-up",
    personaName: "Tim",
    roleTitle: "Follow-up Agent",
    department: "sales",
    tagline: "Kein offenes Angebot bleibt mehr liegen",
    description:
      "Erkennt unbeantwortete Leads und offene Angebote, schlägt angemessene Follow-ups vor, erstellt Nachrichtenentwürfe und plant freigegebene Erinnerungen — mit automatischem Stopp bei Antwort oder Ablehnung.",
    responsibilities: [
      "Unbeantwortete Leads und offene Angebote erkennen",
      "Angemessene Follow-ups mit Begründung vorschlagen",
      "Nachrichtenentwürfe erstellen",
      "Freigegebene Erinnerungen planen",
      "Sequenzen bei Antwort oder Ablehnung stoppen",
    ],
    boundaries: [
      "Kein Versand ohne Freigabe oder ausdrücklich erlaubte Standardregel",
      "Respektiert Opt-outs, Sperrvermerke und Kontaktfrequenz-Regeln",
      "Ändert keine Angebotsinhalte oder Preise",
    ],
    kpis: [
      { key: "followed_up", label: "Nachverfolgte Chancen", unit: "Anzahl" },
      { key: "reply_rate", label: "Antwortquote", unit: "%" },
      { key: "reactivated_deals", label: "Reaktivierte Deals", unit: "Anzahl" },
      { key: "pipeline_secured", label: "Gesicherter Pipeline-Wert (Schätzung)", unit: "€" },
    ],
    capabilities: [
      {
        key: "opportunity-watch",
        name: "Chancen-Überwachung",
        description: "Erkennt Deals und Leads ohne Antwort innerhalb definierter Fristen.",
        defaultAutomationLevel: 1,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["deals.read", "crm.read", "email.read"],
      },
      {
        key: "followup-drafting",
        name: "Follow-up-Entwürfe",
        description:
          "Erstellt personalisierte Follow-up-Nachrichten und legt sie zur Freigabe vor; nach Genehmigung erfolgt der Versand.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 3,
        riskLevel: "high",
        requiredTools: ["deals.read", "email.draft", "email.send"],
      },
      {
        key: "followup-send",
        name: "Versand nach Freigabe",
        description: "Versendet freigegebene Follow-ups über die E-Mail-Integration.",
        defaultAutomationLevel: 3,
        // Versand nach außen bleibt freigabepflichtig (Spec §4.11).
        maxAutomationLevel: 3,
        riskLevel: "high",
        requiredTools: ["email.send", "crm.write"],
      },
    ],
    requiredIntegrations: ["email", "crm"],
    dataRequirements: ["CRM mit Deals/Angeboten", "E-Mail-Postfach"],
    priceTier: "advanced",
    securityLevel: "elevated",
    implementationDepth: "deep",
  }),

  defineAgent({
    slug: "proposal",
    personaName: "Sara",
    roleTitle: "Proposal Agent",
    department: "sales",
    tagline: "Angebote aus Ihren Daten — regelkonform kalkuliert",
    description:
      "Erstellt Angebote aus CRM-, Gesprächs- und Produktdaten auf Basis freigegebener Vorlagen, prüft Pflichtfelder, berechnet Preise ausschließlich nach hinterlegten Regeln und dokumentiert Versionen.",
    responsibilities: [
      "Angebotsentwürfe aus CRM-, Gesprächs- und Produktdaten erstellen",
      "Freigegebene Vorlagen verwenden und Pflichtfelder prüfen",
      "Preise ausschließlich nach hinterlegten Regeln berechnen",
      "PDF-Entwürfe erzeugen und Freigabeprozesse starten",
      "Angebotsversionen dokumentieren",
    ],
    boundaries: [
      "Keine eigenständige Änderung von Preisen außerhalb erlaubter Regeln",
      "Kein Versand ohne Freigabe",
      "Kennzeichnet fehlende Pflichtangaben statt sie zu erfinden",
    ],
    kpis: [
      { key: "proposals_drafted", label: "Erstellte Angebotsentwürfe", unit: "Anzahl" },
      { key: "field_completeness", label: "Pflichtfeld-Vollständigkeit", unit: "%" },
      { key: "approval_time", label: "Zeit bis Freigabe", unit: "Stunden" },
    ],
    capabilities: [
      {
        key: "proposal-drafting",
        name: "Angebotserstellung",
        description: "Erstellt Angebotsentwürfe aus Vorlagen und CRM-Daten.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 3,
        riskLevel: "high",
        requiredTools: ["crm.read", "deals.read", "documents.write", "pricing.calculate"],
      },
      {
        key: "field-validation",
        name: "Pflichtfeld-Prüfung",
        description: "Prüft Angebote auf Vollständigkeit und Regelkonformität.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["documents.read"],
      },
      {
        key: "version-tracking",
        name: "Versionsdokumentation",
        description: "Verwaltet Angebotsversionen und Änderungshistorie.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["documents.read", "documents.write"],
      },
    ],
    requiredIntegrations: ["crm"],
    optionalIntegrations: ["files"],
    dataRequirements: ["Angebotsvorlagen", "Preis- und Rabattregeln", "Produktkatalog"],
    priceTier: "complex",
    securityLevel: "elevated",
    setupEffort: "high",
  }),

  defineAgent({
    slug: "crm-agent",
    personaName: "Nico",
    roleTitle: "CRM Agent",
    department: "sales",
    tagline: "Ihr CRM — endlich vollständig und aktuell",
    description:
      "Erstellt und aktualisiert CRM-Einträge, ergänzt Gesprächszusammenfassungen, erkennt Dubletten, meldet unvollständige Datensätze und legt Folgeaufgaben an.",
    responsibilities: [
      "CRM-Einträge erstellen und aktualisieren",
      "Gesprächszusammenfassungen ergänzen",
      "Dubletten und unvollständige Datensätze erkennen",
      "Deal-Phasen nur nach definierten Regeln verschieben",
      "Folgeaufgaben anlegen",
    ],
    boundaries: [
      "Löscht keine Datensätze ohne Freigabe",
      "Verschiebt Deal-Phasen ausschließlich regelbasiert",
      "Überschreibt keine manuellen Einträge ohne Kennzeichnung",
    ],
    kpis: [
      { key: "records_updated", label: "Aktualisierte Datensätze", unit: "Anzahl" },
      { key: "duplicates_found", label: "Erkannte Dubletten", unit: "Anzahl" },
      { key: "data_completeness", label: "Datenvollständigkeit", unit: "%" },
    ],
    capabilities: [
      {
        key: "record-maintenance",
        name: "Datensatzpflege",
        description: "Erstellt und aktualisiert Kontakte, Firmen und Deals.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "medium",
        requiredTools: ["crm.read", "crm.write"],
      },
      {
        key: "duplicate-detection",
        name: "Dubletten-Erkennung",
        description: "Erkennt und meldet doppelte Einträge mit Zusammenführungsvorschlag.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "medium",
        requiredTools: ["crm.read"],
      },
      {
        key: "task-creation",
        name: "Folgeaufgaben",
        description: "Legt Folgeaufgaben nach definierten Regeln an.",
        defaultAutomationLevel: 3,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["tasks.write"],
      },
    ],
    requiredIntegrations: ["crm"],
    dataRequirements: ["CRM-Zugang", "Regeln für Deal-Phasen"],
    priceTier: "simple",
  }),

  defineAgent({
    slug: "meeting-preparation",
    personaName: "Emma",
    roleTitle: "Meeting Preparation Agent",
    department: "sales",
    tagline: "Perfekt vorbereitet in jedes Kundengespräch",
    description:
      "Erstellt vor Meetings ein Briefing: bisherige Kommunikation, offene Aufgaben und Angebote, freigegebene Unternehmensinformationen sowie Fragen und Gesprächsziele — Unsicherheiten werden gekennzeichnet.",
    responsibilities: [
      "Vor Meetings ein strukturiertes Briefing erstellen",
      "Bisherige Kommunikation zusammenfassen",
      "Offene Aufgaben und Angebote anzeigen",
      "Freigegebene Unternehmensinformationen recherchieren",
      "Fragen und Gesprächsziele vorschlagen",
      "Unsicherheiten und fehlende Informationen kennzeichnen",
    ],
    boundaries: [
      "Nutzt nur freigegebene Datenquellen",
      "Erfindet keine Informationen — Lücken werden ausgewiesen",
      "Teilt Briefings nur mit berechtigten Teilnehmern",
    ],
    kpis: [
      { key: "briefings_created", label: "Erstellte Briefings", unit: "Anzahl" },
      { key: "on_time_rate", label: "Rechtzeitig vor Termin", unit: "%" },
      { key: "usefulness", label: "Als hilfreich bewertet", unit: "%" },
    ],
    capabilities: [
      {
        key: "meeting-briefing",
        name: "Meeting-Briefing",
        description: "Erstellt quellenbasierte Briefings vor anstehenden Terminen.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["calendar.read", "crm.read", "email.read", "knowledge.search", "briefing.write"],
      },
      {
        key: "question-suggestions",
        name: "Fragen & Gesprächsziele",
        description: "Schlägt Fragen und Ziele für das Gespräch vor.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["crm.read", "knowledge.search"],
      },
    ],
    requiredIntegrations: ["calendar"],
    optionalIntegrations: ["crm", "email"],
    dataRequirements: ["Kalenderzugang", "CRM-Historie (optional)"],
    priceTier: "advanced",
    setupEffort: "low",
    implementationDepth: "deep",
  }),

  defineAgent({
    slug: "sales-reporting",
    personaName: "Paul",
    roleTitle: "Sales Reporting Agent",
    department: "sales",
    tagline: "Funnel-Kennzahlen und Forecasts ohne Excel-Nächte",
    description:
      "Erstellt Tages-, Wochen- und Monatsberichte, berechnet Funnel-Kennzahlen, erkennt gefährdete Deals und erstellt Forecasts mit ausgewiesener Unsicherheit.",
    responsibilities: [
      "Tages-, Wochen- und Monatsberichte erstellen",
      "Funnel-Kennzahlen berechnen",
      "Gefährdete Deals erkennen",
      "Forecasts mit Unsicherheitsangabe erstellen",
      "Nächste Maßnahmen vorschlagen",
    ],
    boundaries: [
      "Keine erfundenen Zahlen — jede Kennzahl ist auf Daten zurückführbar",
      "Forecasts werden immer mit Unsicherheit und Annahmen ausgewiesen",
      "Unvollständige Datengrundlagen werden gekennzeichnet",
    ],
    kpis: [
      { key: "reports_generated", label: "Erstellte Berichte", unit: "Anzahl" },
      { key: "at_risk_flagged", label: "Erkannte gefährdete Deals", unit: "Anzahl" },
      { key: "data_coverage", label: "Datenabdeckung", unit: "%" },
    ],
    capabilities: [
      {
        key: "funnel-reporting",
        name: "Funnel-Berichte",
        description: "Berechnet und visualisiert Funnel-Kennzahlen aus dem CRM.",
        defaultAutomationLevel: 4,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["crm.read", "deals.read", "reports.generate"],
      },
      {
        key: "deal-risk",
        name: "Deal-Risiko-Erkennung",
        description: "Erkennt stagnierende oder gefährdete Deals.",
        defaultAutomationLevel: 1,
        maxAutomationLevel: 4,
        riskLevel: "low",
        requiredTools: ["deals.read", "notify.send"],
      },
      {
        key: "forecast",
        name: "Forecast",
        description: "Erstellt Prognosen mit ausgewiesener Unsicherheit.",
        defaultAutomationLevel: 2,
        maxAutomationLevel: 3,
        riskLevel: "medium",
        requiredTools: ["deals.read", "reports.generate"],
      },
    ],
    requiredIntegrations: ["crm"],
    dataRequirements: ["CRM mit gepflegten Deal-Phasen und Werten"],
    priceTier: "advanced",
  }),
];
